[[libunistring]]
arch = "aarch64"
git-tree-sha1 = "59c40908d17690de25f4b594cc2c989cd15ea743"
os = "macos"

    [[libunistring.download]]
    sha256 = "7d26b75093321a881071246cf184fef8375ce05dfd174e710d3bd36ec760662c"
    url = "https://github.com/JuliaBinaryWrappers/libunistring_jll.jl/releases/download/libunistring-v1.4.1+0/libunistring.v1.4.1.aarch64-apple-darwin.tar.gz"
[[libunistring]]
arch = "aarch64"
git-tree-sha1 = "7cdd3b0cd5cbf984433931e7f8086f86aabd67b8"
libc = "glibc"
os = "linux"

    [[libunistring.download]]
    sha256 = "99e4c15602e14d0799e934308daaa37e55d415f21a67ce1369a4a9199cf09bdd"
    url = "https://github.com/JuliaBinaryWrappers/libunistring_jll.jl/releases/download/libunistring-v1.4.1+0/libunistring.v1.4.1.aarch64-linux-gnu.tar.gz"
[[libunistring]]
arch = "aarch64"
git-tree-sha1 = "368cc2313fee30ccd3ccbe31a10f77dce6705558"
libc = "musl"
os = "linux"

    [[libunistring.download]]
    sha256 = "8893f4740492efe916ea783085b5a81e520a14f628e8c285775fb162393d6805"
    url = "https://github.com/JuliaBinaryWrappers/libunistring_jll.jl/releases/download/libunistring-v1.4.1+0/libunistring.v1.4.1.aarch64-linux-musl.tar.gz"
[[libunistring]]
arch = "aarch64"
git-tree-sha1 = "3a9b894dda6d0ef8772fbb75db81a4aba55239fa"
os = "freebsd"

    [[libunistring.download]]
    sha256 = "69665cb1a001a2b68e935c8e9914257bbfdd441b5bc633cee2b122a04b9d0518"
    url = "https://github.com/JuliaBinaryWrappers/libunistring_jll.jl/releases/download/libunistring-v1.4.1+0/libunistring.v1.4.1.aarch64-unknown-freebsd.tar.gz"
[[libunistring]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b8058dc2ba49d9c5ad2f08efb74b9c39d1119862"
libc = "glibc"
os = "linux"

    [[libunistring.download]]
    sha256 = "8bf1e3bb471b5b95d01ed6a8be0f2ed4006735dd95ef7e0f5a0a79057938fb54"
    url = "https://github.com/JuliaBinaryWrappers/libunistring_jll.jl/releases/download/libunistring-v1.4.1+0/libunistring.v1.4.1.armv6l-linux-gnueabihf.tar.gz"
[[libunistring]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "466624f7ae4a367ebdb6da1771119474994c9bb4"
libc = "musl"
os = "linux"

    [[libunistring.download]]
    sha256 = "d887b9232114dfe9d4f75a226f2e7d19232a8a2875b8e3a35ddcd16a2e5f02e2"
    url = "https://github.com/JuliaBinaryWrappers/libunistring_jll.jl/releases/download/libunistring-v1.4.1+0/libunistring.v1.4.1.armv6l-linux-musleabihf.tar.gz"
[[libunistring]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b940ca1986ec85bfba083e4266f7d19a91cae42e"
libc = "glibc"
os = "linux"

    [[libunistring.download]]
    sha256 = "7355ef15e2f9ea84625b02ae36b09c6e947bf29f6f38464b90c8ac62b26604e9"
    url = "https://github.com/JuliaBinaryWrappers/libunistring_jll.jl/releases/download/libunistring-v1.4.1+0/libunistring.v1.4.1.armv7l-linux-gnueabihf.tar.gz"
[[libunistring]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9d698a04ef97a96ec66f56779ec1c5023a8678f4"
libc = "musl"
os = "linux"

    [[libunistring.download]]
    sha256 = "ad6153a00ca3441d03b31358423ba07f2b988c304397a0c500f174fc26f476ac"
    url = "https://github.com/JuliaBinaryWrappers/libunistring_jll.jl/releases/download/libunistring-v1.4.1+0/libunistring.v1.4.1.armv7l-linux-musleabihf.tar.gz"
[[libunistring]]
arch = "i686"
git-tree-sha1 = "c80b25f7c61a176ec244fcd6eb91de81d3162b0c"
libc = "glibc"
os = "linux"

    [[libunistring.download]]
    sha256 = "1de43ff80fd9f5f0d6494b146ceebe301dbf5de38c382ec388c4c1c5a8fdbb1c"
    url = "https://github.com/JuliaBinaryWrappers/libunistring_jll.jl/releases/download/libunistring-v1.4.1+0/libunistring.v1.4.1.i686-linux-gnu.tar.gz"
[[libunistring]]
arch = "i686"
git-tree-sha1 = "10ffc9a5b0c91f8bd876f189719e9ed8706b00e2"
libc = "musl"
os = "linux"

    [[libunistring.download]]
    sha256 = "ac4d71b7066e6ecb2f02e14e7976925890b9ecb23b12abc09ec672cb9ce67c3d"
    url = "https://github.com/JuliaBinaryWrappers/libunistring_jll.jl/releases/download/libunistring-v1.4.1+0/libunistring.v1.4.1.i686-linux-musl.tar.gz"
[[libunistring]]
arch = "i686"
git-tree-sha1 = "29e51734795506ccbffb13f2af4263fca6c81588"
os = "windows"

    [[libunistring.download]]
    sha256 = "31bc23a452d5f97f73d576f1c25b785303e01eedad2b4c9a0caca516d665a502"
    url = "https://github.com/JuliaBinaryWrappers/libunistring_jll.jl/releases/download/libunistring-v1.4.1+0/libunistring.v1.4.1.i686-w64-mingw32.tar.gz"
[[libunistring]]
arch = "powerpc64le"
git-tree-sha1 = "1182c9e7d4ae0cdc912a6045cb20432e150d713a"
libc = "glibc"
os = "linux"

    [[libunistring.download]]
    sha256 = "7c1a7f1c66f99fd1e239b0718634b2d05326066b20e1b0e4baa03639b484648b"
    url = "https://github.com/JuliaBinaryWrappers/libunistring_jll.jl/releases/download/libunistring-v1.4.1+0/libunistring.v1.4.1.powerpc64le-linux-gnu.tar.gz"
[[libunistring]]
arch = "riscv64"
git-tree-sha1 = "46663c09023d55e8ef5458113bf3e0f0e92cd11f"
libc = "glibc"
os = "linux"

    [[libunistring.download]]
    sha256 = "55cccb12241e16427d3b71636d3f24bca766eb1783f8527cc531bdc248f7a222"
    url = "https://github.com/JuliaBinaryWrappers/libunistring_jll.jl/releases/download/libunistring-v1.4.1+0/libunistring.v1.4.1.riscv64-linux-gnu.tar.gz"
[[libunistring]]
arch = "x86_64"
git-tree-sha1 = "9d51eb3323f2c5d0da141a5ebe16da112345feb1"
os = "macos"

    [[libunistring.download]]
    sha256 = "6d69bd2998223036e07a28391ce645127d9cb18422569fdf942fdaa912bf4480"
    url = "https://github.com/JuliaBinaryWrappers/libunistring_jll.jl/releases/download/libunistring-v1.4.1+0/libunistring.v1.4.1.x86_64-apple-darwin.tar.gz"
[[libunistring]]
arch = "x86_64"
git-tree-sha1 = "796b4e7da32d3f475927c0a87bdbf4e150409270"
libc = "glibc"
os = "linux"

    [[libunistring.download]]
    sha256 = "b8ff60904c043fde2b78142686cc5776d074c95e137d90f117b1976500c39eea"
    url = "https://github.com/JuliaBinaryWrappers/libunistring_jll.jl/releases/download/libunistring-v1.4.1+0/libunistring.v1.4.1.x86_64-linux-gnu.tar.gz"
[[libunistring]]
arch = "x86_64"
git-tree-sha1 = "98b9a8793a591977fe79747c34a3efdb99b3bd7b"
libc = "musl"
os = "linux"

    [[libunistring.download]]
    sha256 = "7f97c8f171341b7b6cbbfc61af533f904667e190e404dd764423c0ae0c2d0e52"
    url = "https://github.com/JuliaBinaryWrappers/libunistring_jll.jl/releases/download/libunistring-v1.4.1+0/libunistring.v1.4.1.x86_64-linux-musl.tar.gz"
[[libunistring]]
arch = "x86_64"
git-tree-sha1 = "65c8ba49aba4a8c8d58e9deb9846295de3fae71c"
os = "freebsd"

    [[libunistring.download]]
    sha256 = "5c224e6cf1ff80975701ead312041df3ff3ed488d6dc7870fe1b2cba0db5321f"
    url = "https://github.com/JuliaBinaryWrappers/libunistring_jll.jl/releases/download/libunistring-v1.4.1+0/libunistring.v1.4.1.x86_64-unknown-freebsd.tar.gz"
[[libunistring]]
arch = "x86_64"
git-tree-sha1 = "240b4147674bab6f2f83f7a8959963ea59001eb2"
os = "windows"

    [[libunistring.download]]
    sha256 = "4c0008c2dff052629c07a5dd81fdf7309abef9249214514bac2175c4a20dd3fa"
    url = "https://github.com/JuliaBinaryWrappers/libunistring_jll.jl/releases/download/libunistring-v1.4.1+0/libunistring.v1.4.1.x86_64-w64-mingw32.tar.gz"
